### ISSUE TITLE
Make entire release card clickable

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#103]
When I navigate to a label or artist page, for example: https://dlcm.app/mystery-circles, I should be able to click the entire card to go to [the release page](https://dlcm.app/mystery-circles/chord-memory) since that's the only action you can take. Currently, you can only click the title or image. There should also be some visual feedback on hover.

<img width="516" alt="Screenshot 2023-07-06 at 11 16 41 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/29cc6a6d-5924-43c5-aed4-75a0914da8b7">

**Comment by frankmarra** [comment]
implemented in PR #112
