### ISSUE TITLE
Album Photos Disappearing Randomly 

### ISSUE THREAD

**Issue by MysteryCircles** [frankmarra/DLCM#122]
Seems some album photos are disappearing after being fine for a time period. 
see screenshot. the 2 showing a DLCM image are well under 1mb and were displaying fine... until they weren't 

<img width="1045" alt="Screen Shot 2023-07-11 at 3 25 28 PM" src="https://github.com/frankmarra/DLCM/assets/138532900/0663c848-b58b-4ddb-8ec7-02f9fb1d3858">

**Comment by frankmarra** [comment]
This was resolved in PR #123
