### ISSUE TITLE
Conditionally render the about section on a release page

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#164]
If I release doesn't have any "about" text, then don't render the empty element. [Example release](https://dlcm.app/revolt-against-sanity/cool) without about text.

<img width="445" alt="Screenshot 2023-08-22 at 7 05 10 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/94672508-770a-43f8-a37f-b5cd51266ce0">

**Comment by frankmarra** [comment]
Fixed in PR #167
