### ISSUE TITLE
Update release page meta information

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#165]
The release page meta title and description could be improved by including the artist name. In the screenshot for the [example page](https://dlcm.app/mystery-circles/orbitalpatterns-these-haunted-objects), I imagine it being something like this:

- `title`: These Haunted Objects by Orbitalpatterns | DLCM
- `description`: Get a download code for These Haunted Objects by Orbitalpatterns

<img width="400" alt="Screenshot 2023-08-22 at 7 11 20 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/f1320263-271c-4623-ab8f-6a7fd0add2c4">

**Comment by frankmarra** [comment]
Fixed in PR #167
