### ISSUE TITLE
Add a redirect for /login page

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#34]
When you navigate to https://unrivaled-pie-1255ea.netlify.app/login, it just shows some "Loading..." text and does nothing. Note that I am experiencing this as an anonymous user.

This should do the following:

* **Anonymous**: Show login form on this page  _or_ `301` redirect to homepage. Check out [Netlify docs](https://docs.netlify.com/routing/redirects/) on redirects.
* **Authenticated**: Redirect to user dashboard.

**Comment by frankmarra** [comment]
added with netlify.toml
