### ISSUE TITLE
Improve UX after creating a new account

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#35]
If it's possible, once I create a new account, log me in and send me to my dashboard. Currently I see the following text:

> **New User Created**
> Thank you for signing up! Please sign in to access your dashboard.
> [Sign In](https://unrivaled-pie-1255ea.netlify.app/)

If this is not an easy thing to do, then update the text to:

> **An [artist/label] account has been created for [artist/label name]**
> Thanks for signing up! [Log in](https://unrivaled-pie-1255ea.netlify.app/) to access your dashboard.

**Comment by hexagoncircle** [comment]
This language may also be dependent on https://github.com/frankmarra/DLCM/issues/37

> **An [artist/label] account has been created for [artist/label name]**
> Thanks for signing up! Check your email for a confirmation link to access your dashboard.

**Comment by frankmarra** [comment]
done did it.
