### ISSUE TITLE
Ensure action copy and urls for logging in are consistent

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#36]
I noticed that you can navigate to `/login` but then action buttons say "Sign in". The more common term to use is "Log in".

* "Sign in" can be confusing with "Sign up"—"Log in" sets a clearer delineation.
* "Sign in" can hint the need to do other things upon signing in, sort of like what you'd do in schools or going through work security checks. "Log in" is, in my (garbage) opinion, specific to computer speak with user accounts.

Whatever does get used, be sure that it's the same throughout the site.

**Comment by frankmarra** [comment]
changed.
