### ISSUE TITLE
Add client-side password creation validation

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#38]
If I "re-enter password" and then [blur](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/blur) the field, it should display some text telling me that the re-entered value doesn't currently match the value in the "password" input. Once they do match, the error hint can disappear.

Currently:
<img width="300" alt="Screenshot 2023-06-17 at 12 01 11 PM" src="https://github.com/frankmarra/DLCM/assets/1704038/7b3bfee3-17d0-4f9d-a530-fa085b5003f7">

Proposed:
<img width="300" alt="Screenshot 2023-06-17 at 12 04 14 PM" src="https://github.com/frankmarra/DLCM/assets/1704038/a969cc26-bf67-4466-9db2-3f0a2aedbcc2">

**Comment by frankmarra** [comment]
done. not using blur. just using a conditional.
