### ISSUE TITLE
Client-side validation of Artist or Label name

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#39]
When I create my account, I don't know if an artist or label already exists with the same name. There should be some sort of feedback to let me know.

This could potentially be based on the unique path for the artist/label instead. If so, the `slug` input field would need to be added to the user signup form. The same rules would apply where there needs to be some client-side validation and an error hint.

<img width="320" alt="Screenshot 2023-06-17 at 12 08 05 PM" src="https://github.com/frankmarra/DLCM/assets/1704038/aabe8115-b50a-48ce-b181-01ec29554347">

**Comment by frankmarra** [comment]
I think I did this, though sans the slug part.
