### ISSUE TITLE
Reset password email went to spam folder and link not supplied

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#40]
See screenshot below. This went to my spam folder. It may be for a few reasons, but the top one would be where the email was sent from.

* Email came from: `noreply@mail.app.supabase.io`. This should be `noreply@downloadcodemanager.com` or whatever the url should be.
* A reset password link needs to be added.
* Change subject line: 
> Reset your Download Code Manager password
* Change body copy:
> There was a request to reset the password for the account associated with this email.
> Follow this link to create a new password for this account: Reset password

* Add link to "Reset password" text that will allow user to reset password.

<img width="600" alt="Screenshot 2023-06-17 at 12 31 43 PM" src="https://github.com/frankmarra/DLCM/assets/1704038/b3c8d528-c2df-48f7-a3b4-f847209a3aac">

### Helpful resources

* https://postmarkapp.com/guides/password-reset-email-best-practices

**Comment by frankmarra** [comment]
No longer an issue as of 8-20-23
