### ISSUE TITLE
Clean up user dashboard profile UI

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#41]
The profile container could benefit from some visual tweaks. Here are a few off the top of my head but this ticket can also handle any other visual changes related to this component.

### Profile container

<img width="600" alt="Screenshot 2023-06-18 at 8 15 43 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/f215f48d-2b05-452e-8d8d-2c8ecd7f092b">

- [x] Add a placeholder image or edit icon where profile image will eventually appear. If edit icon, clicking on it should open the "Update profile" modal.
- [x] Add some space between artist and free user badges
- [x] Find better position for "Subscribe" link.

### Update profile modal
- [x] Add placeholder image when no image is set. A dashed border where image will appear would suffice.
- [x] When an image exists, change "Upload image" to "Replace profile image"
<img width="300" alt="Screenshot 2023-06-18 at 8 23 49 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/8cd52e82-f8c1-4753-a1a0-56aaeabaa9e0">

- [x] Move `username` input under its "Username" label.
- [x] Change "Username" label to "Artist/Label Name".
- [x] Add a hint/description under Input for "Redemption(yum) Link"—I don't know what this is. I assume bandcampers will get it but there should still be some succinct help text here, potentially linking to documentation on what it is (if available).
- [x] Convert the url (specifically the `slug` part of it) so it's editable; Handle any UX/functional changes in https://github.com/frankmarra/DLCM/issues/42

**Comment by frankmarra** [comment]
fully completed as of https://github.com/frankmarra/DLCM/pull/56
