### ISSUE TITLE
Generating and changing a profile slug

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#42]
When I click "Update profile" and start changing my user name, it automatically updates the profile `slug`. Instead, the `slug` should remain unchanged. If the user wants to change their url, they should do it manually.

When first signing up, the user should be able to see their automatically generated `slug`.
* `slug` should automatically generate when user blurs the field—it will need to check the database to ensure the url doesn't exist already.
* User should have option to change generated `slug`.
* If they do edit the `slug`, it should disable automatic generation. Editing the artist/label name input again would not affect the `slug` at this point.

**Comment by frankmarra** [comment]
Implemented in https://github.com/frankmarra/DLCM/pull/56
