### ISSUE TITLE
Clarify artwork upload experience when adding a new release

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#44]
- [x] Add an "Artwork" label above the "Upload image" button so it's clear what this is doing.
- [x] It's unclear what the "Artwork" input if for until I upload an image. Change label to "Artwork URL".
- [x] Add hint text under "Artwork URL": "Upload a custom image or paste an external link to your artwork"
<img width="300" alt="Screenshot 2023-06-18 at 8 56 53 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/08be50ce-66ec-43ef-951a-a472404f9616">

**Comment by frankmarra** [comment]
Good call. FInished.
