### ISSUE TITLE
Rearrange the action buttons in the update release modal

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#45]
When I click the "edit" button on a release, a modal opens with three buttons to update, delete, or cancel. These controls should be grouped a bit differently to remove some cognitive load here. I've attached a very loose example as an improvement to this experience.

- [x] Group the "Update" and "Cancel" buttons
- [x] Visually hide "Delete" text. Add trash icon from [phosphor icons](https://phosphoricons.com/) (I think that's the icon set being used on the site)
- [x] Change "Delete" button color to red.

<img width="300" alt="Screenshot 2023-06-18 at 9 04 44 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/2bcbd4f7-bd4a-485f-b78c-7084551be638">
<img width="300" alt="Screenshot 2023-06-18 at 9 09 29 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/905334c9-3a20-4c5f-94fd-acf2aa171ef7">

**Comment by frankmarra** [comment]
in next PR
