### ISSUE TITLE
Add fallback image for any broken image sources

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#46]
Check out my second release in this screenshot. I was able to just enter spaces in the release, artist, and label fields. I also just wrote a bunch of characters in the "Artwork" field, which obviously produces a broken image. The broken image should be replaced with a fallback/default image.

<img width="600" alt="Screenshot 2023-06-18 at 9 14 59 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/634571f9-de6a-4c2f-8647-a6b0e3663d2e">

**Side note:** It might be worth peppering the inputs with some validation so I couldn't just enter a space without any other characters. But one could argue that's what the artist wants.

**Comment by frankmarra** [comment]
will be in next pull request
