### ISSUE TITLE
Add clearer hint text in adding codes modal

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#47]
Right now it says "Enter manually" which wasn't totally clear to me. Tell me a bit more about what I'm supposed to do here. "Paste your codes from Bandcamp below" maybe?

<img width="300" alt="Screenshot 2023-06-18 at 9 22 35 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/a1522e4d-9e75-4dfb-8150-9af504472ec2">

**Comment by frankmarra** [comment]
Good call. This is because when you become a pro member, you are able to upload via the CSV that bandcamp gives you.
