### ISSUE TITLE
Do not render containers or labels if fields are empty

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#51]
If the user hasn't supplied information for a particular field, then don't display the elements related to it. For example, on a [release page](https://unrivaled-pie-1255ea.netlify.app/revolt-against-sanity/high-school-is-a-drag), the "social sites" label shouldn't be rendered since there aren't any to show.

<img width="600" alt="Screenshot 2023-06-18 at 11 11 13 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/a5995b58-0a83-473a-8385-0bdf516853ee">

**Comment by frankmarra** [comment]
Fixed in next code push
