### ISSUE TITLE
Update design of release page template

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#52]
The release page layout needs some love! Check out [this example](https://unrivaled-pie-1255ea.netlify.app/revolt-against-sanity/high-school-is-a-drag) where the page is definitely lacking focused design thinking.

**Comment by frankmarra** [comment]
Updated the styling a bit in PR #60

**Comment by hexagoncircle** [comment]
Handled in https://github.com/frankmarra/DLCM/pull/138
