### ISSUE TITLE
Update slug on sign up form

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#57]
- Change "Public Address" to be "Public URL will be:" or "Public Artist URL will be:"
- Add forward slash after hostname, it's currently missing before slug: "Public Address: https://dlcm.app/my-slug"
- Change "Urls taken, try again" to "This URL is already in use"

Side note: Bandcamp's [signup page](https://bandcamp.com/signup) has a "username" field, which is what generates the unique slug, or subdomain in their case (my-band.bandcamp.com). Would it be clearer if someone signing up had to choose a username instead of a slug?

**Comment by frankmarra** [comment]
Fixed in PR #60

**Comment by frankmarra** [comment]
Fixed in PR #60
