### ISSUE TITLE
Favicon improvements

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#73]
The current favicon image just doesn't work quite well. I'd like to suggest changing it so that:

- It's easier to see what it is.
- It has a background color so that it's visually accessible on light and dark color schemes.
 
<img width="200" alt="Screenshot 2023-07-03 at 11 02 17 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/24b09c8d-9116-44c3-b8a8-191c8724c0a4">

**Comment by frankmarra** [comment]
Addressed in PR #116
