### ISSUE TITLE
Standardize text casing in the app

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#74]
Use the screenshot below as a reference:

- "artist" should be "Artist"
- "Free user" should be "Free user"—debatable if categories (badge text) should use title casing though!
- "Update Profile" should be "Update profile"—use sentence casing for actions in CTA buttons
 
<img width="500" alt="Screenshot 2023-07-03 at 11 06 30 AM" src="https://github.com/frankmarra/DLCM/assets/1704038/2d5cc097-6b22-4a3f-a8e2-a3d3d4d71f1a">

**Comment by frankmarra** [comment]
Fixed in PR #79
