### ISSUE TITLE
Remove section width causing horizontal overflow

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#78]
Setting `width: 50ch` on the home page about section text causes unwanted horizontal overflow. It's rare that a strict width or height value ever needs to be set.

<img width="800" alt="Screenshot 2023-07-03 at 1 14 12 PM" src="https://github.com/frankmarra/DLCM/assets/1704038/f42cd2a4-7c76-4a2a-b863-e5bd35c8aed8">

Instead, since this uses the `inline-max` selector, set the available CSS variable to the desired value: `style="--max-inline-size: 50ch"`

**Comment by frankmarra** [comment]
Fixed in PR #79
