### ISSUE TITLE
Social links need text labels

### ISSUE THREAD

**Issue by hexagoncircle** [frankmarra/DLCM#81]
All links need to have some text associated with them. If you inspect these social link icons, you'll see that they _only_ have svg icons.

<img width="400" alt="Screenshot 2023-07-03 at 2 39 21 PM" src="https://github.com/frankmarra/DLCM/assets/1704038/992d3d8f-f7d4-4cc0-b117-52cc03cc31f8">

You could add labels and hide them visually, for example:

```html
<a href="#">
  <span class="visually-hidden">Visit profile on Bandcamp</span>
  <svg>...</svg>
</a>
```

Keep them short but descriptive:
- Visit profile on Bandcamp
- Listen on Spotify
- Listen on Soundcloud

**Comment by frankmarra** [comment]
Addressed in PR #117
