### ISSUE TITLE
Editing Release Level URLs 

### ISSUE THREAD

**Issue by MysteryCircles** [frankmarra/DLCM#84]
Release level URL should have ability to change in case of spelling, forgetting to set album type, etc. 
"Choose release type" shows up if nothing entered - can this be blank if they don't choose anything?

**Comment by frankmarra** [comment]
I don't think the release level urls should have the ability to be changed. If an artist does this and does not understand what they are doing, they will render all previous links completely worthless, as it has the wrong address.

**Comment by MysteryCircles** [comment]
Ok - we should at least update the ability to go back and set the release type if they forget / make an error! (like i did ha)

**Comment by frankmarra** [comment]
implemented in pr #99
