### ISSUE TITLE
Password protect issues 

### ISSUE THREAD

**Issue by MysteryCircles** [frankmarra/DLCM#88]
Putting this up as it is a priority issue. Profile PW protection doesn't seem to be working properly. 
I was able to set up a password for my profile page, but when I unchecked it, it's still password protected. 
Other user (Oscillog) set PW protection but it is not showing up. 

Album level password protect seems to be working properly so you may want to look at what you have there vs. profile! 

Also, when password protected, it would be ideal to at least show the label name / logo (not just a blank page) 
Example: https://downloadcodemanager.com/labels/psoma-psi-phi

**Comment by frankmarra** [comment]
Fixed in #94
