### ISSUE TITLE
Add info to sign up link 

### ISSUE THREAD

**Issue by MysteryCircles** [frankmarra/DLCM#91]
When clicking on sign up at the bottom, it takes you to the sign up page. Should pro account info be there? Or does it get offered clearly once someone creates a user account?

**Comment by frankmarra** [comment]
Will add this, but I want to refine that section first. Will work on that over the next couple of days. I think all of the copy is written under the assumption that people know what download codes are. I think we need to make it clearer what the service is.

**Comment by MysteryCircles** [comment]
Agreed, but not a priority until fully marketing this which won't start until we're working well word of mouth.

**Comment by frankmarra** [comment]
Added in PR #112
