### ISSUE TITLE
E-mail account activation to prevent spam 

### ISSUE THREAD

**Issue by MysteryCircles** [frankmarra/DLCM#92]
Should new sign ups get an email to confirm their account before being able to use?

**Comment by frankmarra** [comment]
We can do that. Ryan had mentioned it. The only reason I have not implemented is because our emails go to spam.

**Comment by MysteryCircles** [comment]
Gotcha. Not priority. We can keep it in mind!

**Comment by frankmarra** [comment]
This has been resolved in PR #126
